### ISSUE TITLE
email and txt services seem to be failing

### ISSUE THREAD

**Issue by jrochkind** [team-umlaut/umlaut#19]
Failing in master even before bootstrap merge. 

```
  EmailExport:
    type: EmailExport
    priority: d

  TxtHoldingExport:
    type: TxtHoldingExport
    priority: d
```
